/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/emhass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Emhass Status */
        get: operations["emhass_status_api_emhass_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emhass/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emhass Check */
        post: operations["emhass_check_api_emhass_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emhass/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emhass Discover
         * @description Search for EMHASS again (only used when Settings → EMHASS → address is empty).
         */
        post: operations["emhass_discover_api_emhass_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: log, run.*, job.updated, settings.changed, ... (comma-separated prefixes).
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ha/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ha Entities
         * @description Entities for the settings pickers (cached for 30 s).
         */
        get: operations["ha_entities_api_ha_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness for the Supervisor watchdog: answers as long as the event loop does.
         */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inputs
         * @description What an MPC run would use right now, with where every value comes from.
         */
        get: operations["inputs_api_inputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Job */
        post: operations["pause_job_api_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_api_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Job
         * @description Start the job now; answers with the new run's id as soon as the run exists.
         */
        post: operations["run_job_api_jobs__job_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legacy/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Legacy Apply */
        post: operations["legacy_apply_api_legacy_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legacy/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Preview
         * @description What importing the HACS integration's settings would change.
         */
        get: operations["legacy_preview_api_legacy_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logs
         * @description Log history, newest last. Combines the database with the newest lines not yet flushed.
         */
        get: operations["logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mpc/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mpc Preview
         * @description Build and check the MPC payload as if a run started now. Nothing is sent.
         */
        post: operations["mpc_preview_api_mpc_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan
         * @description The newest EMHASS plan (and the one before it), with prices on the same slots.
         */
        get: operations["plan_api_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prices
         * @description Priced 15-minute slots from local midnight `days_back` days ago to the end of the forecast.
         */
        get: operations["prices_api_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problems */
        get: operations["problems_api_problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_runs__run_id__artifacts__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Bundle
         * @description Everything about one run in a single JSON file, for bug reports.
         */
        get: operations["run_bundle_api_runs__run_id__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Logs */
        get: operations["run_logs_api_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Run */
        post: operations["pin_run_api_runs__run_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /**
         * Put Settings
         * @description Replace the whole settings document (the form sends everything it shows).
         */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Settings
         * @description Change some fields; nested objects merge, lists and values replace.
         */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/settings/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Yaml
         * @description The current settings as YAML (secrets masked; importing the file keeps the stored secrets).
         */
        get: operations["export_yaml_api_settings_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Yaml
         * @description Preview (dry_run) or apply a YAML settings file. Missing keys fall back to defaults.
         */
        post: operations["import_yaml_api_settings_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/revert/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert */
        post: operations["revert_api_settings_revert__revision__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_settings_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/revisions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision */
        get: operations["revision_api_settings_revisions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description JSON schema of the settings with UI hints (json_schema_extra.ui), $refs inlined.
         */
        get: operations["get_schema_api_settings_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Used by the UI to notice an App update or restart and offer a reload.
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactInfo */
        ArtifactInfo: {
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Size */
            size: number;
        };
        /** ComponentStatus */
        ComponentStatus: {
            /** Detail */
            detail?: string | null;
            /** Status */
            status: string;
        };
        /** DeferrableLoad */
        DeferrableLoad: {
            /**
             * Deadline (time steps from now) from
             * @description Number of 15-minute steps from now by which the load must be done; 0 = no deadline.
             * @default sensor.ev_charging_timesteps
             */
            deadline_timesteps_entity: string;
            /**
             * Enabled when on
             * @default input_boolean.ev_charging_enabled
             */
            enabled_entity: string;
            /**
             * Name
             * @default EV
             */
            name: string;
            /**
             * Power
             * @default 11000
             */
            nominal_power_w: number;
            /**
             * Operating hours from
             * @default sensor.ev_operating_hours
             */
            operating_hours_entity: string;
            /**
             * Run in one block when on
             * @default input_boolean.ev_force_continuous_charging
             */
            single_constant_entity: string;
        };
        /** DiffEntry */
        DiffEntry: {
            /** New */
            new?: unknown;
            /** Old */
            old?: unknown;
            /** Path */
            path: string;
        };
        /** EeForecast */
        EeForecast: {
            /**
             * API key
             * @description eupowerprices.com API key.
             * @default
             */
            api_key: string;
            /**
             * Poll every
             * @default 1
             */
            poll_hours: number;
        };
        /** Emhass */
        Emhass: {
            /**
             * EMHASS address
             * @description Base URL of the EMHASS App, e.g. http://5b918bf2-emhass:5000. Leave empty to look it up through the Supervisor.
             * @default
             */
            base_url: string;
            /**
             * Extra runtime parameters
             * @description Added to every MPC payload as-is (shown in each run's Explain view).
             */
            extra_runtime_params?: {
                [key: string]: unknown;
            };
            /**
             * ML load forecast
             * @default {
             *       "historic_days": 30,
             *       "n_trials": 10,
             *       "sklearn_model": "KNeighborsRegressor",
             *       "var_model": "sensor.house_power_without_deferrable"
             *     }
             */
            ml: components["schemas"]["EmhassMl"];
            /**
             * Mode
             * @description Off: never calls EMHASS actions. Dry run: builds and checks every payload but does not send it. Live: runs and publishes.
             * @default off
             * @enum {string}
             */
            mode: "off" | "dry_run" | "live";
            /**
             * MPC optimization
             * @default {
             *       "auto": false,
             *       "hazard_guard_s": 30,
             *       "max_horizon": 672,
             *       "min_horizon": 8,
             *       "slot_offset_s": 780
             *     }
             */
            mpc: components["schemas"]["EmhassMpc"];
            /**
             * Publishing
             * @default {
             *       "enabled": true,
             *       "slot_offset_s": 2
             *     }
             */
            publish: components["schemas"]["EmhassPublish"];
            /**
             * Timeouts
             * @default {
             *       "fit": 3600,
             *       "mpc": 180,
             *       "predict": 180,
             *       "publish": 60,
             *       "tune": 7200
             *     }
             */
            timeouts: components["schemas"]["EmhassTimeouts"];
        };
        /** EmhassMl */
        EmhassMl: {
            /**
             * Training history
             * @default 30
             */
            historic_days: number;
            /**
             * Tuning trials
             * @default 10
             */
            n_trials: number;
            /**
             * Lags
             * @description Leave empty to derive it like before: 192 + 96 × forecast extension days.
             */
            num_lags?: number | null;
            /**
             * Model type
             * @default KNeighborsRegressor
             * @enum {string}
             */
            sklearn_model: "KNeighborsRegressor" | "RandomForestRegressor" | "GradientBoostingRegressor" | "RidgeRegression" | "MLPRegressor";
            /**
             * Load sensor for the ML model
             * @description The household power sensor (without deferrable loads) EMHASS learns from.
             * @default sensor.house_power_without_deferrable
             */
            var_model: string;
        };
        /** EmhassMpc */
        EmhassMpc: {
            /**
             * Run MPC automatically
             * @description Run naive-mpc-optim every quarter-hour. Only acts when the mode is dry run or live.
             * @default false
             */
            auto: boolean;
            /**
             * Grid-boundary guard
             * @description Older EMHASS versions (< 0.18.2) can fail when a run starts within this many seconds of a slot rounding boundary; the run waits it out.
             * @default 30
             */
            hazard_guard_s: number;
            /**
             * Maximum horizon
             * @description Cap the number of slots sent to EMHASS.
             * @default 672
             */
            max_horizon: number;
            /**
             * Minimum horizon
             * @description Refuse to run when fewer future slots than this have prices.
             * @default 8
             */
            min_horizon: number;
            /**
             * Run at (seconds into each quarter)
             * @description 780 = mm:13:00, two minutes before the next quarter starts, so the plan for the next slot is ready before it is published.
             * @default 780
             */
            slot_offset_s: number;
        };
        /** EmhassPublish */
        EmhassPublish: {
            /**
             * Publish each quarter
             * @description Call publish-data right after each quarter starts (live mode), so EMHASS's sensor.p_* entities show the slot that just began.
             * @default true
             */
            enabled: boolean;
            /**
             * Publish at (seconds into each quarter)
             * @default 2
             */
            slot_offset_s: number;
        };
        /** EmhassStatusOut */
        EmhassStatusOut: {
            /** Checks */
            checks: {
                [key: string]: unknown;
            }[];
            /** Checks Status */
            checks_status: string;
            /** Config At */
            config_at: string | null;
            /** Discovery */
            discovery: {
                [key: string]: unknown;
            }[];
            /** Health */
            health: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error: string | null;
            /** Last Health At */
            last_health_at: string | null;
            /** Method Ts Round */
            method_ts_round: string;
            /** Mpc */
            mpc: {
                [key: string]: unknown;
            };
            /** Reachable */
            reachable: boolean | null;
            /** Unreachable Since */
            unreachable_since: string | null;
            /** Url */
            url: string | null;
            /** Url Source */
            url_source: string | null;
            /** Version */
            version: string | null;
        };
        /** EmhassTimeouts */
        EmhassTimeouts: {
            /**
             * ML fit
             * @default 3600
             */
            fit: number;
            /**
             * MPC
             * @default 180
             */
            mpc: number;
            /**
             * ML predict
             * @default 180
             */
            predict: number;
            /**
             * Publish
             * @default 60
             */
            publish: number;
            /**
             * ML tune
             * @default 7200
             */
            tune: number;
        };
        /** EntityInput */
        EntityInput: {
            /** Default */
            default?: number | null;
            /** Entity */
            entity: string;
            /**
             * When unavailable
             * @description Refuse: skip the run and raise a problem. Default: use the value below.
             * @default refuse
             * @enum {string}
             */
            on_unavailable: "refuse" | "default";
            /**
             * Multiply by
             * @description 0.01 turns a percentage into the 0–1 EMHASS expects.
             * @default 0.01
             */
            scale: number;
        };
        /** EntityOption */
        EntityOption: {
            /** Device Class */
            device_class: string | null;
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string | null;
            /** State */
            state: string | null;
            /** Unit */
            unit: string | null;
        };
        /** FiForecast */
        FiForecast: {
            /**
             * Attribute with the forecast list
             * @default forecast
             */
            attribute: string;
            /**
             * Forecast entity
             * @default sensor.nordpool_predict_fi_price
             */
            entity: string;
            /**
             * Unit
             * @default c_per_kwh
             * @enum {string}
             */
            unit: "c_per_kwh" | "eur_per_kwh" | "eur_per_mwh";
            /**
             * VAT included in the values
             * @description Removed before Estonian tariffs are applied. 0 if the values exclude VAT.
             * @default 0
             */
            vat_included_pct: number;
        };
        /** Forecast */
        Forecast: {
            /**
             * eupowerprices.com
             * @default {
             *       "api_key": "",
             *       "poll_hours": 1
             *     }
             */
            ee: components["schemas"]["EeForecast"];
            /**
             * Extend by
             * @default 1
             */
            extend_days: number;
            /**
             * nordpool-predict-fi
             * @default {
             *       "attribute": "forecast",
             *       "entity": "sensor.nordpool_predict_fi_price",
             *       "unit": "c_per_kwh",
             *       "vat_included_pct": 0
             *     }
             */
            fi: components["schemas"]["FiForecast"];
            /**
             * Price forecast
             * @description Extends the price horizon beyond the published day-ahead prices.
             * @default none
             * @enum {string}
             */
            source: "none" | "ee_eupowerprices" | "fi_ha_entity";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Plan is stale after
             * @default 2
             */
            plan_max_age_slots: number;
            /**
             * Notify after a problem lasts
             * @default 10
             */
            problem_grace_min: number;
            /**
             * Error if tomorrow's prices are missing after
             * @default 18:00
             */
            tomorrow_error_after: string;
            /**
             * Warn if tomorrow's prices are missing after
             * @default 15:30
             */
            tomorrow_warn_after: string;
        };
        /** ImportPreview */
        ImportPreview: {
            /** Diff */
            diff: components["schemas"]["DiffEntry"][];
            /** Errors */
            errors: {
                [key: string]: string;
            }[];
            /** Revision */
            revision?: number | null;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Base Revision */
            base_revision?: number | null;
            /** Comment */
            comment?: string | null;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Yaml */
            yaml: string;
        };
        /** Inputs */
        Inputs: {
            /** Deferrable loads */
            deferrable_loads?: components["schemas"]["DeferrableLoad"][];
            /**
             * Battery state of charge at the end of the horizon
             * @default {
             *       "default": 0.8,
             *       "entity": "input_number.emhass_target_soc",
             *       "on_unavailable": "default",
             *       "scale": 0.01
             *     }
             */
            soc_final: components["schemas"]["EntityInput"];
            /**
             * Battery state of charge now
             * @default {
             *       "entity": "sensor.ev6_battery_soc",
             *       "on_unavailable": "refuse",
             *       "scale": 0.01
             *     }
             */
            soc_init: components["schemas"]["EntityInput"];
        };
        /** InputsResponse */
        InputsResponse: {
            /** Forecast */
            forecast: {
                [key: string]: unknown;
            };
            /** Home Assistant */
            home_assistant: {
                [key: string]: unknown;
            };
            /** Mpc */
            mpc: {
                [key: string]: unknown;
            };
            /** Pv */
            pv: {
                [key: string]: unknown;
            };
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
        };
        /** JobInfo */
        JobInfo: {
            /** Description */
            description: string;
            /** Grace S */
            grace_s: number;
            /** Id */
            id: string;
            /** Last Finished */
            last_finished: string | null;
            /** Last Outcome */
            last_outcome: string | null;
            /** Last Run Id */
            last_run_id: number | null;
            /** Last Started */
            last_started: string | null;
            /** Next Run */
            next_run: string | null;
            /** Paused */
            paused: boolean;
            /** Running */
            running: boolean;
            /** Title */
            title: string;
            /** Trigger */
            trigger: string;
        };
        /** LegacyApplyRequest */
        LegacyApplyRequest: {
            /** Base Revision */
            base_revision?: number | null;
        };
        /** LegacyPreview */
        LegacyPreview: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Diff */
            diff: components["schemas"]["DiffEntry"][];
            /** Errors */
            errors: {
                [key: string]: string;
            }[];
            /** Found */
            found: boolean;
            /** Notes */
            notes: string[];
        };
        /** LogEntry */
        LogEntry: {
            /** Component */
            component: string;
            /** Exc */
            exc?: string | null;
            /** Id */
            id: number;
            /** Job */
            job?: string | null;
            /** Level */
            level: string;
            /** Msg */
            msg: string;
            /** Run Id */
            run_id?: number | null;
            /** Ts */
            ts: string;
        };
        /** Logging */
        Logging: {
            /**
             * Per-component levels
             * @description e.g. {"emhass": "debug"} for more detail from one part only.
             */
            component_levels?: {
                [key: string]: "debug" | "info" | "warning" | "error";
            };
            /**
             * Log level
             * @description Default follows the log_level option in the App's Configuration tab.
             * @default default
             * @enum {string}
             */
            level: "default" | "debug" | "info" | "warning" | "error";
            /**
             * @default {
             *       "artifacts_days": 7,
             *       "logs_days": 7,
             *       "runs_days": 30
             *     }
             */
            retention: components["schemas"]["Retention"];
        };
        /** MpcPreview */
        MpcPreview: {
            /** Anchor */
            anchor: string;
            /** Built At */
            built_at: string;
            /** Derived */
            derived: {
                [key: string]: unknown;
            };
            /** Explain */
            explain: {
                [key: string]: unknown;
            }[];
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Mode */
            mode: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Rounding */
            rounding: string;
            /** Validation */
            validation: {
                [key: string]: unknown;
            }[];
        };
        /** NetworkRates */
        NetworkRates: {
            /**
             * Day
             * @default 0.0369
             */
            day: number;
            /**
             * Day peak
             * @description Working days 09–12 and 16–20, November–March. Empty = no peak rate.
             */
            day_peak?: number | null;
            /**
             * Weekend peak
             * @description Weekends and holidays 16–20, November–March. Empty = no peak rate.
             */
            holiday_peak?: number | null;
            /**
             * Night / weekend / holiday
             * @default 0.021
             */
            night: number;
        };
        /** NightWindow */
        NightWindow: {
            /**
             * Clock
             * @description Local: the window follows the wall clock. Standard time: it is defined in winter time, so in summer it shifts one hour later (e.g. 23–08).
             * @default local
             * @enum {string}
             */
            clock_basis: "local" | "standard_time";
            /**
             * End
             * @default 07:00
             */
            end: string;
            /**
             * Start
             * @default 22:00
             */
            start: string;
        };
        /** NordpoolPolling */
        NordpoolPolling: {
            /**
             * Bidding zone
             * @default EE
             * @enum {string}
             */
            area: "EE" | "FI" | "LV" | "LT";
            /**
             * Fast poll interval
             * @default 5
             */
            fast_interval_min: number;
            /**
             * Poll fast until
             * @default 15:00
             */
            fast_until: string;
            /**
             * Day-ahead results expected at
             * @description Local time from which tomorrow's prices are polled.
             * @default 13:45
             */
            publish_time: string;
            /**
             * Slow poll interval
             * @default 60
             */
            slow_interval_min: number;
        };
        /** Notifications */
        Notifications: {
            /**
             * Home Assistant notifications
             * @description Raise a persistent notification for problems that last longer than the grace time.
             * @default false
             */
            persistent: boolean;
        };
        /** Outputs */
        Outputs: {
            /**
             * Discovery prefix
             * @default homeassistant
             */
            discovery_prefix: string;
            /**
             * Fire an event after each publish
             * @description emhass_lens_plan_published, with the current slot's plan values in the event data.
             * @default true
             */
            fire_event: boolean;
            /**
             * MQTT entities
             * @description Publish the EMHASS Lens device (prices, problem, last MPC, Auto MPC switch, Run MPC button) through MQTT discovery. Needs the Mosquitto broker App.
             * @default false
             */
            mqtt_enabled: boolean;
        };
        /** Parity */
        Parity: {
            /**
             * Compare with the HACS integration
             * @description While the old integration still runs, compare its prices and MPC payload with ours.
             * @default true
             */
            enabled: boolean;
            /**
             * Legacy Auto MPC switch
             * @default switch.nordpool_ee_prices_emhass_auto_mpc
             */
            legacy_auto_mpc_switch: string;
            /**
             * Legacy entity prefix
             * @default nordpool_ee_prices_
             */
            legacy_prefix: string;
            /**
             * Tolerance
             * @default 0.000001
             */
            tolerance: number;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Available */
            available: boolean;
            /** Columns */
            columns: string[];
            current: components["schemas"]["PlanSnapshotOut"] | null;
            /** Current Row */
            current_row: {
                [key: string]: unknown;
            } | null;
            /** Driver */
            driver: string;
            /** Emhass Url */
            emhass_url: string | null;
            previous: components["schemas"]["PlanSnapshotOut"] | null;
            /** Prices */
            prices: {
                [key: string]: unknown;
            }[];
        };
        /** PlanSnapshotOut */
        PlanSnapshotOut: {
            /** Driver */
            driver: string;
            /** Fetched At */
            fetched_at: string;
            /** Generated At */
            generated_at: string;
            /** Last Run */
            last_run?: {
                [key: string]: unknown;
            } | null;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Run Id */
            run_id?: number | null;
        };
        /** PriceSlotOut */
        PriceSlotOut: {
            /** Balancing */
            balancing: number;
            /** End */
            end: string;
            /** Excise */
            excise: number;
            /** Export Fees */
            export_fees: number;
            /** Export Price */
            export_price: number;
            /** Import Price */
            import_price: number;
            /** Margin */
            margin: number;
            /** Network */
            network: number;
            /** Origin */
            origin: string;
            /** Period */
            period: string;
            /** Reason */
            reason: string;
            /** Renewable */
            renewable: number;
            /** Spot */
            spot: number;
            /** Start */
            start: string;
            /** Supply Security */
            supply_security: number;
            /** Tariff Ex Vat */
            tariff_ex_vat: number;
            /** Vat */
            vat: number;
        };
        /** Prices */
        Prices: {
            /**
             * Nord Pool day-ahead
             * @default {
             *       "area": "EE",
             *       "fast_interval_min": 5,
             *       "fast_until": "15:00",
             *       "publish_time": "13:45",
             *       "slow_interval_min": 60
             *     }
             */
            nordpool: components["schemas"]["NordpoolPolling"];
            /**
             * @default {
             *       "balancing": 0.00373,
             *       "excise": 0.0021,
             *       "export_balancing": 0.00373,
             *       "export_margin": 0.01,
             *       "margin": 0.00328,
             *       "network": {
             *         "day": 0.0369,
             *         "night": 0.021
             *       },
             *       "night_window": {
             *         "clock_basis": "local",
             *         "end": "07:00",
             *         "start": "22:00"
             *       },
             *       "package": "custom",
             *       "renewable": 0.0084,
             *       "supply_security": 0.00758,
             *       "vat_pct": 24
             *     }
             */
            tariff: components["schemas"]["Tariff"];
        };
        /** PricesResponse */
        PricesResponse: {
            /** Actual End */
            actual_end: string | null;
            /** Forecast */
            forecast: {
                [key: string]: unknown;
            };
            /** Forecast Until */
            forecast_until: string | null;
            /** Gaps */
            gaps: string[][];
            /** Nordpool */
            nordpool: {
                [key: string]: unknown;
            };
            /** Now */
            now: string;
            /** Package */
            package: string;
            /** Slots */
            slots: components["schemas"]["PriceSlotOut"][];
            /** Timezone */
            timezone: string;
        };
        /** ProblemInfo */
        ProblemInfo: {
            /** Detail */
            detail?: string | null;
            /** Hint */
            hint?: string | null;
            /** Key */
            key: string;
            /** Link */
            link?: string | null;
            /** Severity */
            severity: string;
            /** Since */
            since?: string | null;
            /** Title */
            title: string;
        };
        /** ProblemsResponse */
        ProblemsResponse: {
            /** Active */
            active: components["schemas"]["ProblemInfo"][];
            /** History */
            history: {
                [key: string]: unknown;
            }[];
        };
        /** Pv */
        Pv: {
            /**
             * Days to read
             * @default 7
             */
            days: number;
            /**
             * Solcast sensor prefix
             * @description Day sensors are <prefix>today, <prefix>tomorrow, <prefix>day_3 … day_7.
             * @default sensor.solcast_pv_forecast_forecast_
             */
            entity_prefix: string;
            /**
             * Estimate
             * @default from_select
             * @enum {string}
             */
            field: "from_select" | "estimate" | "estimate10" | "estimate90";
            /**
             * Solcast select entity
             * @default select.solcast_pv_forecast_use_forecast_field
             */
            field_select_entity: string;
            /**
             * Multiply by
             * @default 1
             */
            scale: number;
            /**
             * PV forecast
             * @default solcast
             * @enum {string}
             */
            source: "solcast" | "none";
        };
        /** Retention */
        Retention: {
            /**
             * Keep run details
             * @default 7
             */
            artifacts_days: number;
            /**
             * Keep logs
             * @default 7
             */
            logs_days: number;
            /**
             * Keep run summaries
             * @default 30
             */
            runs_days: number;
        };
        /** RevertRequest */
        RevertRequest: {
            /** Base Revision */
            base_revision?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /** Revision */
        Revision: {
            /** Actor */
            actor: string | null;
            /** Comment */
            comment: string | null;
            /** Created At */
            created_at: string;
            /** Diff */
            diff: components["schemas"]["DiffEntry"][];
            /** Id */
            id: number;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactInfo"][];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: number;
            /** Job */
            job: string;
            /** Mode */
            mode?: string | null;
            /** Outcome */
            outcome: string;
            /**
             * Pinned
             * @default 0
             */
            pinned: number;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Settings Rev */
            settings_rev?: number | null;
            /** Started At */
            started_at: string;
            /** Summary */
            summary?: string | null;
            /** Trigger */
            trigger: string;
        };
        /** RunStarted */
        RunStarted: {
            job: components["schemas"]["JobInfo"];
            /** Run Id */
            run_id: number | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: number;
            /** Job */
            job: string;
            /** Mode */
            mode?: string | null;
            /** Outcome */
            outcome: string;
            /**
             * Pinned
             * @default 0
             */
            pinned: number;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Settings Rev */
            settings_rev?: number | null;
            /** Started At */
            started_at: string;
            /** Summary */
            summary?: string | null;
            /** Trigger */
            trigger: string;
        };
        /** SaveResponse */
        SaveResponse: {
            /** Diff */
            diff: components["schemas"]["DiffEntry"][];
            /** Revision */
            revision: number;
        };
        /** Settings */
        Settings: {
            /**
             * EMHASS
             * @default {
             *       "base_url": "",
             *       "extra_runtime_params": {},
             *       "ml": {
             *         "historic_days": 30,
             *         "n_trials": 10,
             *         "sklearn_model": "KNeighborsRegressor",
             *         "var_model": "sensor.house_power_without_deferrable"
             *       },
             *       "mode": "off",
             *       "mpc": {
             *         "auto": false,
             *         "hazard_guard_s": 30,
             *         "max_horizon": 672,
             *         "min_horizon": 8,
             *         "slot_offset_s": 780
             *       },
             *       "publish": {
             *         "enabled": true,
             *         "slot_offset_s": 2
             *       },
             *       "timeouts": {
             *         "fit": 3600,
             *         "mpc": 180,
             *         "predict": 180,
             *         "publish": 60,
             *         "tune": 7200
             *       }
             *     }
             */
            emhass: components["schemas"]["Emhass"];
            /**
             * Price forecast
             * @default {
             *       "ee": {
             *         "api_key": "",
             *         "poll_hours": 1
             *       },
             *       "extend_days": 1,
             *       "fi": {
             *         "attribute": "forecast",
             *         "entity": "sensor.nordpool_predict_fi_price",
             *         "unit": "c_per_kwh",
             *         "vat_included_pct": 0
             *       },
             *       "source": "none"
             *     }
             */
            forecast: components["schemas"]["Forecast"];
            /**
             * @default {
             *       "plan_max_age_slots": 2,
             *       "problem_grace_min": 10,
             *       "tomorrow_error_after": "18:00",
             *       "tomorrow_warn_after": "15:30"
             *     }
             */
            health: components["schemas"]["Health"];
            /**
             * @default {
             *       "deferrable_loads": [
             *         {
             *           "deadline_timesteps_entity": "sensor.ev_charging_timesteps",
             *           "enabled_entity": "input_boolean.ev_charging_enabled",
             *           "name": "EV",
             *           "nominal_power_w": 11000,
             *           "operating_hours_entity": "sensor.ev_operating_hours",
             *           "single_constant_entity": "input_boolean.ev_force_continuous_charging"
             *         }
             *       ],
             *       "soc_final": {
             *         "default": 0.8,
             *         "entity": "input_number.emhass_target_soc",
             *         "on_unavailable": "default",
             *         "scale": 0.01
             *       },
             *       "soc_init": {
             *         "entity": "sensor.ev6_battery_soc",
             *         "on_unavailable": "refuse",
             *         "scale": 0.01
             *       }
             *     }
             */
            inputs: components["schemas"]["Inputs"];
            /**
             * @default {
             *       "component_levels": {},
             *       "level": "default",
             *       "retention": {
             *         "artifacts_days": 7,
             *         "logs_days": 7,
             *         "runs_days": 30
             *       }
             *     }
             */
            logging: components["schemas"]["Logging"];
            /**
             * @default {
             *       "persistent": false
             *     }
             */
            notifications: components["schemas"]["Notifications"];
            /**
             * Home Assistant outputs
             * @default {
             *       "discovery_prefix": "homeassistant",
             *       "fire_event": true,
             *       "mqtt_enabled": false
             *     }
             */
            outputs: components["schemas"]["Outputs"];
            /**
             * Parity with the HACS integration
             * @default {
             *       "enabled": true,
             *       "legacy_auto_mpc_switch": "switch.nordpool_ee_prices_emhass_auto_mpc",
             *       "legacy_prefix": "nordpool_ee_prices_",
             *       "tolerance": 0.000001
             *     }
             */
            parity: components["schemas"]["Parity"];
            /**
             * @default {
             *       "nordpool": {
             *         "area": "EE",
             *         "fast_interval_min": 5,
             *         "fast_until": "15:00",
             *         "publish_time": "13:45",
             *         "slow_interval_min": 60
             *       },
             *       "tariff": {
             *         "balancing": 0.00373,
             *         "excise": 0.0021,
             *         "export_balancing": 0.00373,
             *         "export_margin": 0.01,
             *         "margin": 0.00328,
             *         "network": {
             *           "day": 0.0369,
             *           "night": 0.021
             *         },
             *         "night_window": {
             *           "clock_basis": "local",
             *           "end": "07:00",
             *           "start": "22:00"
             *         },
             *         "package": "custom",
             *         "renewable": 0.0084,
             *         "supply_security": 0.00758,
             *         "vat_pct": 24
             *       }
             *     }
             */
            prices: components["schemas"]["Prices"];
            /**
             * PV forecast
             * @default {
             *       "days": 7,
             *       "entity_prefix": "sensor.solcast_pv_forecast_forecast_",
             *       "field": "from_select",
             *       "field_select_entity": "select.solcast_pv_forecast_use_forecast_field",
             *       "scale": 1,
             *       "source": "solcast"
             *     }
             */
            pv: components["schemas"]["Pv"];
        };
        /** SettingsPatchRequest */
        SettingsPatchRequest: {
            /** Base Revision */
            base_revision?: number | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Comment */
            comment?: string | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Errors */
            errors: {
                [key: string]: string;
            }[];
            /** Revision */
            revision: number;
            settings: components["schemas"]["Settings"];
            /** Writable */
            writable: boolean;
            /** Write Block Reason */
            write_block_reason: string | null;
        };
        /** SettingsSaveRequest */
        SettingsSaveRequest: {
            /** Base Revision */
            base_revision?: number | null;
            /** Comment */
            comment?: string | null;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** StatusInfo */
        StatusInfo: {
            /** Actor */
            actor: string;
            /** Components */
            components: {
                [key: string]: components["schemas"]["ComponentStatus"];
            };
            /**
             * Driver
             * @default none
             */
            driver: string;
            /** Emhass Mode */
            emhass_mode: string;
            /** Problems */
            problems: components["schemas"]["ProblemInfo"][];
            /** Safe Mode */
            safe_mode: boolean;
            /** Scheduler Running */
            scheduler_running: boolean;
            /** Settings Errors */
            settings_errors: {
                [key: string]: string;
            }[];
            /** Settings Revision */
            settings_revision: number;
            /** Started At */
            started_at: string;
            /** Timezone */
            timezone: string;
            /** Under Supervisor */
            under_supervisor: boolean;
            /** Version */
            version: string;
            /** Writable */
            writable: boolean;
            /** Write Block Reason */
            write_block_reason: string | null;
        };
        /** Tariff */
        Tariff: {
            /**
             * Balancing capacity fee (tasakaalustamine)
             * @default 0.00373
             */
            balancing: number;
            /**
             * Electricity excise (aktsiis)
             * @default 0.0021
             */
            excise: number;
            /**
             * Export balancing fee
             * @default 0.00373
             */
            export_balancing: number;
            /**
             * Export margin
             * @default 0.01
             */
            export_margin: number;
            /**
             * Seller margin
             * @default 0.00328
             */
            margin: number;
            /**
             * Network rates (custom package)
             * @default {
             *       "day": 0.0369,
             *       "night": 0.021
             *     }
             */
            network: components["schemas"]["NetworkRates"];
            /**
             * Night rate hours
             * @default {
             *       "clock_basis": "local",
             *       "end": "07:00",
             *       "start": "22:00"
             *     }
             */
            night_window: components["schemas"]["NightWindow"];
            /**
             * Network package
             * @description Elektrilevi Võrk 1/2/4/5 bring their own network rates; Custom uses the rates below.
             * @default custom
             * @enum {string}
             */
            package: "vork1" | "vork2" | "vork4" | "vork5" | "custom";
            /**
             * Renewable energy fee (taastuvenergia tasu)
             * @default 0.0084
             */
            renewable: number;
            /**
             * Security of supply fee (varustuskindlus)
             * @default 0.00758
             */
            supply_security: number;
            /**
             * VAT
             * @default 24
             */
            vat_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionInfo */
        VersionInfo: {
            /** Started At */
            started_at: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    emhass_status_api_emhass_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmhassStatusOut"];
                };
            };
        };
    };
    emhass_check_api_emhass_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
        };
    };
    emhass_discover_api_emhass_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmhassStatusOut"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                topics?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ha_entities_api_ha_entities_get: {
        parameters: {
            query?: {
                /** @description Comma-separated domains, e.g. sensor,input_number */
                domain?: string | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    inputs_api_inputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputsResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"][];
                };
            };
        };
    };
    pause_job_api_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_api_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_job_api_jobs__job_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_apply_api_legacy_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    legacy_preview_api_legacy_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyPreview"];
                };
            };
        };
    };
    logs_api_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
                level?: string;
                component?: string | null;
                run_id?: number | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mpc_preview_api_mpc_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MpcPreview"];
                };
            };
        };
    };
    plan_api_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    prices_api_prices_get: {
        parameters: {
            query?: {
                days_back?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    problems_api_problems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemsResponse"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                job?: string | null;
                outcome?: string | null;
                limit?: number;
                before?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_runs__run_id__artifacts__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_bundle_api_runs__run_id__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_logs_api_runs__run_id__logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_run_api_runs__run_id__pin_post: {
        parameters: {
            query?: {
                pinned?: boolean;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_yaml_api_settings_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    import_yaml_api_settings_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_api_settings_revert__revision__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revisions_api_settings_revisions_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revision_api_settings_revisions__revision__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_settings_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusInfo"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
