// What each kind of run artifact is called on screen.

export const ARTIFACT_NAMES: Record<string, string> = {
  event: 'Event sent to Home Assistant',
  inputs: 'Inputs',
  request: 'Request sent',
  explain: 'Explain',
  validation: 'Validation',
  response: 'Response',
  emhass_last_run: 'EMHASS last run',
  plan: 'Plan',
  checks: 'Configuration checks',
  emhass_config: 'EMHASS configuration',
  parity: 'Parity report',
  forecast: 'Forecast',
  next: 'Next fetches',
  last_run: 'EMHASS last run',
  decision: 'Inverter decision',
  calls: 'Service calls',
  readback: 'Read back',
  comparison: 'Compared with the automation',
  charger_decision: 'Charger decision',
  charger_calls: 'Service calls',
  charger_readback: 'Read back',
  charger_comparison: 'Compared with the automation',
  resume: 'Resume steps',
  market_decision: 'Market decision',
  market_comparison: 'Compared with the automation',
  notification: 'Phone message',
  handback_calls: 'Hand-back calls',
}
